[package]
name = "guitk"
version = "0.1.0"
authors = ["Thomas Cheng <thomascheng1998@googlemail.com>"]

[dependencies]
android_glue = "0.2.1"
ffi_glue = {path = "ffi_glue"}
glium = "*"
libc = "*"
time = "*"
